development: &db
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: phonebook_development
  pool: 15
  username: root
  password:

test:
  <<: *db
  database: phonebook_test

production:
  <<: *db
  database: phonebook_production
